// Network environment - for local network multi-user testing
// This file is auto-generated by setup-network-testing.ps1
// Update the IP address below with your local network IP

export const environment = {
  production: false,
  apiUrl: 'http://YOUR_LOCAL_IP:5000',  // Replace YOUR_LOCAL_IP with your actual IP (e.g., 192.168.1.100)
  apiVersion: ''
};
